name: Deploy Key Vault to Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Add this secret

jobs:
  deploy-key-vault-prod:
    name: Deploy Key Vault to Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install latest Bicep
        run: az bicep upgrade
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set subscription context
      - name: Set Azure Subscription
        run: |
          az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      # Deploy Key Vault to existing demo-rg (RG deployment)
      - name: Deploy Key Vault Prod
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: RnD-RaghavRG
          template: main.bicep
          parameters: param.bicepparam 

